packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  esbuild: true

catalog:
  "@jsonforms/core": "^3.8.0"
  "@jsonforms/examples": "^3.8.0"
onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
  - playwright
