packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@hugeicons/svelte': true
  esbuild: true

overrides:
  jiti: 2.6.1
  lightningcss: 1.30.2

catalog:
  "@jsonforms/core": "^3.9.0-alpha.1"
  "@jsonforms/examples": "^3.9.0-alpha.1"
onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
  - playwright
