import {
  BracesIcon,
  CalendarClockIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleAlertIcon,
  Clock3Icon,
  Dice5Icon,
  EyeIcon,
  EyeOffIcon,
  GithubIcon,
  LaptopMinimalCheckIcon,
  ListIcon,
  MenuIcon,
  MoonIcon,
  PaletteIcon,
  PanelsTopLeftIcon,
  PencilIcon,
  PlusIcon,
  RotateCcwIcon,
  SaveIcon,
  SearchIcon,
  Settings2Icon,
  SunIcon,
  Trash2Icon,
  XIcon,
} from '@lucide/svelte';
import {
  IconAlertCircle,
  IconBraces,
  IconBrandGithub,
  IconCalendar,
  IconCalendarClock,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconChevronUp,
  IconClock,
  IconDeviceFloppy,
  IconDeviceLaptop,
  IconDice5,
  IconEye,
  IconEyeOff,
  IconLayoutSidebar,
  IconList,
  IconMenu2,
  IconMoon,
  IconPalette,
  IconPencil,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSettings2,
  IconSun,
  IconTrash,
  IconX,
} from '@tabler/icons-svelte';
import {
  AlertCircleIcon,
  ArrowDown01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  BracesIcon as HugeBracesIcon,
  Calendar03Icon,
  CalendarAdd01Icon,
  Cancel01Icon,
  Clock01Icon,
  Delete02Icon,
  DiceIcon,
  FloppyDiskIcon,
  GithubIcon as HugeGithubIcon,
  LaptopIcon,
  LeftToRightListBulletIcon,
  Menu01Icon,
  Moon02Icon,
  PaintBoardIcon,
  PencilEdit01Icon,
  PlusSignIcon,
  ReloadIcon,
  Search01Icon,
  Settings02Icon,
  SidebarLeftIcon,
  Sun03Icon,
  Tick02Icon,
  ViewIcon,
  ViewOffIcon,
} from '@hugeicons/core-free-icons';
import BracketsCurly from 'phosphor-svelte/lib/BracketsCurly';
import Calendar from 'phosphor-svelte/lib/Calendar';
import CalendarDots from 'phosphor-svelte/lib/CalendarDots';
import CaretDown from 'phosphor-svelte/lib/CaretDown';
import CaretRight from 'phosphor-svelte/lib/CaretRight';
import CaretUp from 'phosphor-svelte/lib/CaretUp';
import Check from 'phosphor-svelte/lib/Check';
import Clock from 'phosphor-svelte/lib/Clock';
import DiceFive from 'phosphor-svelte/lib/DiceFive';
import Eye from 'phosphor-svelte/lib/Eye';
import EyeClosed from 'phosphor-svelte/lib/EyeClosed';
import FloppyDisk from 'phosphor-svelte/lib/FloppyDisk';
import GearSix from 'phosphor-svelte/lib/GearSix';
import GithubLogo from 'phosphor-svelte/lib/GithubLogo';
import Laptop from 'phosphor-svelte/lib/Laptop';
import List from 'phosphor-svelte/lib/List';
import MagnifyingGlass from 'phosphor-svelte/lib/MagnifyingGlass';
import Moon from 'phosphor-svelte/lib/Moon';
import Palette from 'phosphor-svelte/lib/Palette';
import Pencil from 'phosphor-svelte/lib/Pencil';
import Plus from 'phosphor-svelte/lib/Plus';
import ArrowCounterClockwise from 'phosphor-svelte/lib/ArrowCounterClockwise';
import SidebarSimple from 'phosphor-svelte/lib/SidebarSimple';
import Sun from 'phosphor-svelte/lib/Sun';
import Trash from 'phosphor-svelte/lib/Trash';
import WarningCircle from 'phosphor-svelte/lib/WarningCircle';
import X from 'phosphor-svelte/lib/X';
import {
  RiAddLine,
  RiArrowDownSLine,
  RiArrowRightSLine,
  RiArrowUpSLine,
  RiBracesLine,
  RiCalendarLine,
  RiCalendarScheduleLine,
  RiCheckLine,
  RiCloseLine,
  RiComputerLine,
  RiDeleteBinLine,
  RiDice5Line,
  RiErrorWarningLine,
  RiEyeLine,
  RiEyeOffLine,
  RiGithubLine,
  RiLayoutLeftLine,
  RiListCheck,
  RiMenuLine,
  RiMoonLine,
  RiPaletteLine,
  RiEditLine,
  RiRestartLine,
  RiSaveLine,
  RiSearchLine,
  RiSettings3Line,
  RiSunLine,
  RiTimeLine,
} from 'remixicon-svelte';
import type { IconLibrary } from './icon-library.svelte';

export const iconNames = [
  'braces',
  'calendar-clock',
  'calendar',
  'check',
  'chevron-down',
  'chevron-right',
  'chevron-up',
  'circle-alert',
  'clock',
  'dice',
  'eye',
  'eye-off',
  'github',
  'laptop',
  'list',
  'menu',
  'moon',
  'palette',
  'panels-top-left',
  'pencil',
  'plus',
  'rotate-ccw',
  'save',
  'search',
  'settings',
  'sun',
  'trash',
  'x',
] as const;

export type IconName = (typeof iconNames)[number];

export const componentIcons: Record<Exclude<IconLibrary, 'hugeicons'>, Record<IconName, any>> = {
  lucide: {
    braces: BracesIcon,
    'calendar-clock': CalendarClockIcon,
    calendar: CalendarIcon,
    check: CheckIcon,
    'chevron-down': ChevronDownIcon,
    'chevron-right': ChevronRightIcon,
    'chevron-up': ChevronUpIcon,
    'circle-alert': CircleAlertIcon,
    clock: Clock3Icon,
    dice: Dice5Icon,
    eye: EyeIcon,
    'eye-off': EyeOffIcon,
    github: GithubIcon,
    laptop: LaptopMinimalCheckIcon,
    list: ListIcon,
    menu: MenuIcon,
    moon: MoonIcon,
    palette: PaletteIcon,
    'panels-top-left': PanelsTopLeftIcon,
    pencil: PencilIcon,
    plus: PlusIcon,
    'rotate-ccw': RotateCcwIcon,
    save: SaveIcon,
    search: SearchIcon,
    settings: Settings2Icon,
    sun: SunIcon,
    trash: Trash2Icon,
    x: XIcon,
  },
  tabler: {
    braces: IconBraces,
    'calendar-clock': IconCalendarClock,
    calendar: IconCalendar,
    check: IconCheck,
    'chevron-down': IconChevronDown,
    'chevron-right': IconChevronRight,
    'chevron-up': IconChevronUp,
    'circle-alert': IconAlertCircle,
    clock: IconClock,
    dice: IconDice5,
    eye: IconEye,
    'eye-off': IconEyeOff,
    github: IconBrandGithub,
    laptop: IconDeviceLaptop,
    list: IconList,
    menu: IconMenu2,
    moon: IconMoon,
    palette: IconPalette,
    'panels-top-left': IconLayoutSidebar,
    pencil: IconPencil,
    plus: IconPlus,
    'rotate-ccw': IconRefresh,
    save: IconDeviceFloppy,
    search: IconSearch,
    settings: IconSettings2,
    sun: IconSun,
    trash: IconTrash,
    x: IconX,
  },
  phosphor: {
    braces: BracketsCurly,
    'calendar-clock': CalendarDots,
    calendar: Calendar,
    check: Check,
    'chevron-down': CaretDown,
    'chevron-right': CaretRight,
    'chevron-up': CaretUp,
    'circle-alert': WarningCircle,
    clock: Clock,
    dice: DiceFive,
    eye: Eye,
    'eye-off': EyeClosed,
    github: GithubLogo,
    laptop: Laptop,
    list: List,
    menu: List,
    moon: Moon,
    palette: Palette,
    'panels-top-left': SidebarSimple,
    pencil: Pencil,
    plus: Plus,
    'rotate-ccw': ArrowCounterClockwise,
    save: FloppyDisk,
    search: MagnifyingGlass,
    settings: GearSix,
    sun: Sun,
    trash: Trash,
    x: X,
  },
  remixicon: {
    braces: RiBracesLine,
    'calendar-clock': RiCalendarScheduleLine,
    calendar: RiCalendarLine,
    check: RiCheckLine,
    'chevron-down': RiArrowDownSLine,
    'chevron-right': RiArrowRightSLine,
    'chevron-up': RiArrowUpSLine,
    'circle-alert': RiErrorWarningLine,
    clock: RiTimeLine,
    dice: RiDice5Line,
    eye: RiEyeLine,
    'eye-off': RiEyeOffLine,
    github: RiGithubLine,
    laptop: RiComputerLine,
    list: RiListCheck,
    menu: RiMenuLine,
    moon: RiMoonLine,
    palette: RiPaletteLine,
    'panels-top-left': RiLayoutLeftLine,
    pencil: RiEditLine,
    plus: RiAddLine,
    'rotate-ccw': RiRestartLine,
    save: RiSaveLine,
    search: RiSearchLine,
    settings: RiSettings3Line,
    sun: RiSunLine,
    trash: RiDeleteBinLine,
    x: RiCloseLine,
  },
} as const;

export const hugeIcons = {
  braces: HugeBracesIcon,
  'calendar-clock': CalendarAdd01Icon,
  calendar: Calendar03Icon,
  check: Tick02Icon,
  'chevron-down': ArrowDown01Icon,
  'chevron-right': ArrowRight01Icon,
  'chevron-up': ArrowUp01Icon,
  'circle-alert': AlertCircleIcon,
  clock: Clock01Icon,
  dice: DiceIcon,
  eye: ViewIcon,
  'eye-off': ViewOffIcon,
  github: HugeGithubIcon,
  laptop: LaptopIcon,
  list: LeftToRightListBulletIcon,
  menu: Menu01Icon,
  moon: Moon02Icon,
  palette: PaintBoardIcon,
  'panels-top-left': SidebarLeftIcon,
  pencil: PencilEdit01Icon,
  plus: PlusSignIcon,
  'rotate-ccw': ReloadIcon,
  save: FloppyDiskIcon,
  search: Search01Icon,
  settings: Settings02Icon,
  sun: Sun03Icon,
  trash: Delete02Icon,
  x: Cancel01Icon,
} as const;
