import type { GridOptions, ManagedGridOptions } from 'ag-grid-community';

// AG Grid ignores these after createGrid and reports a warning when they are
// passed to updateGridOptions. Keep the runtime list aligned with AG Grid 36's
// public ManagedGridOptions type.
const initialGridOptionKeys = new Set<keyof GridOptions>([
  'enableBrowserTooltips',
  'tooltipTrigger',
  'tooltipMouseTrack',
  'tooltipShowMode',
  'tooltipInteraction',
  'defaultColGroupDef',
  'suppressAutoSize',
  'skipHeaderOnAutoSize',
  'autoSizeStrategy',
  'components',
  'stopEditingWhenCellsLoseFocus',
  'undoRedoCellEditing',
  'undoRedoCellEditingLimit',
  'excelStyles',
  'cacheQuickFilter',
  'customChartThemes',
  'chartThemeOverrides',
  'chartToolPanelsDef',
  'loadingCellRendererSelector',
  'localeText',
  'keepDetailRows',
  'keepDetailRowsCount',
  'detailRowHeight',
  'detailRowAutoHeight',
  'tabIndex',
  'valueCache',
  'valueCacheNeverExpires',
  'enableCellExpressions',
  'suppressTouch',
  'suppressBrowserResizeObserver',
  'suppressPropertyNamesCheck',
  'debug',
  'dragAndDropImageComponent',
  'overlayComponent',
  'suppressOverlays',
  'loadingOverlayComponent',
  'suppressLoadingOverlay',
  'noRowsOverlayComponent',
  'paginateChildRows',
  'pivotPanelShow',
  'pivotSuppressAutoColumn',
  'suppressExpandablePivotGroups',
  'aggFuncs',
  'allowShowChangeAfterFilter',
  'ensureDomOrder',
  'enableRtl',
  'suppressColumnVirtualisation',
  'suppressMaxRenderedRowRestriction',
  'suppressRowVirtualisation',
  'rowDragText',
  'groupLockGroupColumns',
  'suppressGroupRowsSticky',
  'rowModelType',
  'cacheOverflowSize',
  'infiniteInitialRowCount',
  'serverSideInitialRowCount',
  'maxBlocksInCache',
  'maxConcurrentDatasourceRequests',
  'blockLoadDebounceMillis',
  'serverSideOnlyRefreshFilteredGroups',
  'serverSidePivotResultFieldSeparator',
  'viewportRowModelPageSize',
  'viewportRowModelBufferSize',
  'debounceVerticalScrollbar',
  'suppressAnimationFrame',
  'suppressPreventDefaultOnMouseWheel',
  'scrollbarWidth',
  'icons',
  'suppressRowTransform',
  'suppressContentVisibilityAuto',
  'gridId',
  'enableGroupEdit',
  'initialState',
  'processUnpinnedColumns',
  'createChartContainer',
  'getLocaleText',
  'getRowId',
  'reactiveCustomComponents',
  'renderingMode',
  'columnMenu',
  'suppressSetFilterByDefault',
  'getDataPath',
  'enableCellSpan',
  'enableFilterHandlers',
  'filterHandlers',
]);

export const toManagedGridOptions = <TData>(
  options: GridOptions<TData>,
): ManagedGridOptions<TData> =>
  Object.fromEntries(
    Object.entries(options).filter(
      ([key]) => !initialGridOptionKeys.has(key as keyof GridOptions<TData>),
    ),
  ) as ManagedGridOptions<TData>;
